INSERT INTO COMPOSERS (ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, YEAR_OF_DEATH, GENRE, THUMBNAIL) VALUES (1, 'Franz', 'Schubert', 1797, 1828, 'Romantic', 'schubert.png')
INSERT INTO COMPOSITIONS (ID, COMPOSITION_NAME, COMPOSER_ID) VALUES (1, 'Winterreise', 1)
